"""Generate Bacformer embeddings for Klebsiella genome assemblies (GPU).

This script processes pre-generated protein sequences through the Bacformer pipeline:
1. Loads ESM and Bacformer models once at startup
2. For each genome:
   a. Loads protein sequences from parquet file (generated by generate_protein_sequences.py)
   b. Generates protein embeddings using ESM model (GPU)
   c. Converts embeddings to Bacformer inputs
   d. Generates contextualised Bacformer embeddings (GPU)
   e. Saves ESM embeddings to esm_embeddings/{sample_id}_esm_embeddings.pt
   f. Saves Bacformer embeddings to bacformer_embeddings/{sample_id}_bacformer_embeddings.pt

Note: Models are loaded once and reused for all genomes for efficiency.
Embeddings are saved as separate PyTorch .pt files for efficient storage and loading.
"""

import argparse
import logging
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd
import torch
from bacformer.pp import (
    compute_genome_protein_embeddings,
    load_plm,
    protein_embeddings_to_inputs,
)
from tqdm import tqdm
from transformers import AutoModel

from predict_kleb_by_bacformer.data_paths import data

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("bacformer_embeddings_processing.log"),
    ],
)
logger = logging.getLogger(__name__)


def find_protein_sequence_files(input_dir: Path, limit: int | None = None) -> list[Path]:
    """Find all protein sequence parquet files in the input directory.

    Args:
        input_dir: Directory to search for protein sequence parquet files
        limit: Optional limit on number of files (takes first n if set)

    Returns
    -------
        List of paths to protein sequence parquet files
    """
    logger.info(f"Finding all *_protein_sequences.parquet files in {input_dir}")
    protein_files = sorted(input_dir.glob("*_protein_sequences.parquet"))

    logger.info(f"Found {len(protein_files)} total files")

    if limit:
        protein_files = protein_files[:limit]
        logger.info(f"Processing first {limit} files")

    return protein_files


def extract_sample_id(filepath: Path) -> str:
    """Extract sample ID from protein sequence parquet filepath.

    Example: /path/to/SAMD00052611_protein_sequences.parquet -> SAMD00052611

    Args:
        filepath: Path to the protein sequence parquet file

    Returns
    -------
        Sample ID string
    """
    # The sample ID is the filename without _protein_sequences.parquet suffix
    return filepath.stem.replace("_protein_sequences", "")


def check_embeddings_exist(sample_id: str, esm_dir: Path, bacformer_dir: Path) -> bool:
    """Check if embeddings already exist as .pt files.

    Args:
        sample_id: Sample ID to check
        esm_dir: Directory containing ESM embeddings
        bacformer_dir: Directory containing Bacformer embeddings

    Returns
    -------
        True if both ESM and Bacformer embedding files exist, False otherwise
    """
    esm_file = esm_dir / f"{sample_id}_esm_embeddings.pt"
    bacformer_file = bacformer_dir / f"{sample_id}_bacformer_embeddings.pt"
    return esm_file.exists() and bacformer_file.exists()


def load_protein_sequences(protein_seq_path: Path) -> tuple[str, list]:
    """Load protein sequences from parquet file.

    Args:
        protein_seq_path: Path to the protein sequences parquet file

    Returns
    -------
        Tuple of (sample_id, protein_sequences)
    """
    df = pd.read_parquet(protein_seq_path)
    sample_id = df["sample_id"].iloc[0]
    protein_sequences = df["protein_sequence"].iloc[0]
    return sample_id, protein_sequences


def process_genome_from_protein_sequences(
    protein_seq_path: Path,
    esm_model: torch.nn.Module,
    esm_tokenizer,
    bacformer_model: torch.nn.Module,
    device: str,
    esm_dir: Path,
    bacformer_dir: Path,
    batch_size: int = 128,
    max_proteins: int = 6000,
    max_contigs: int = 1000,
) -> tuple[str, bool, str]:
    """Process a single genome from pre-generated protein sequences.

    Saves ESM and Bacformer embeddings as separate .pt files.

    Args:
        protein_seq_path: Path to the protein sequences parquet file
        esm_model: Loaded ESM model for protein embeddings
        esm_tokenizer: ESM tokenizer
        bacformer_model: Loaded Bacformer model
        device: Device to run inference on
        esm_dir: Directory to save ESM embeddings
        bacformer_dir: Directory to save Bacformer embeddings
        batch_size: Batch size for ESM embedding computation
        max_proteins: Maximum number of proteins per genome
        max_contigs: Maximum number of contigs per genome

    Returns
    -------
        Tuple of (sample_id, success, error_message)
    """
    sample_id = extract_sample_id(protein_seq_path)

    try:
        # Load protein sequences from parquet
        logger.debug(f"Processing {sample_id}: Loading protein sequences")
        _, protein_sequences = load_protein_sequences(protein_seq_path)

        # Generate protein embeddings using ESM model (GPU)
        logger.debug(f"Processing {sample_id}: Generating protein embeddings with ESM")
        protein_embeddings = compute_genome_protein_embeddings(
            model=esm_model,
            tokenizer=esm_tokenizer,
            protein_sequences=protein_sequences,
            model_type="esmc",
            batch_size=batch_size,
            max_prot_seq_len=1024,
            genome_pooling_method=None,
        )

        # Convert protein embeddings to Bacformer inputs
        logger.debug(f"Processing {sample_id}: Converting to Bacformer inputs")
        bacformer_inputs = protein_embeddings_to_inputs(
            protein_embeddings=protein_embeddings,
            max_n_proteins=max_proteins,
            max_n_contigs=max_contigs,
            bacformer_model_type="large",
        )

        # Move inputs to device
        bacformer_inputs = {k: v.to(device) for k, v in bacformer_inputs.items()}

        # Generate Bacformer embeddings (GPU)
        logger.debug(f"Processing {sample_id}: Generating Bacformer embeddings")
        with torch.no_grad():
            bacformer_outputs = bacformer_model(**bacformer_inputs, return_dict=True)

        # Save ESM embeddings (bacformer_inputs) as .pt file
        esm_output_path = esm_dir / f"{sample_id}_esm_embeddings.pt"
        logger.debug(f"Processing {sample_id}: Saving ESM embeddings to {esm_output_path}")
        # Move to CPU and keep as float32 for storage
        esm_embeddings_cpu = {k: v.float().cpu() for k, v in bacformer_inputs.items()}
        torch.save(esm_embeddings_cpu, esm_output_path)

        # Save Bacformer embeddings as .pt file
        bacformer_output_path = bacformer_dir / f"{sample_id}_bacformer_embeddings.pt"
        logger.debug(f"Processing {sample_id}: Saving Bacformer embeddings to {bacformer_output_path}")
        # Save the last hidden state, converted to float32 and moved to CPU
        bacformer_embeddings_cpu = bacformer_outputs["last_hidden_state"].float().cpu()
        torch.save(bacformer_embeddings_cpu, bacformer_output_path)

        return sample_id, True, ""

    except Exception as e:
        error_msg = f"Error processing {sample_id}: {str(e)}"
        logger.error(error_msg)
        return sample_id, False, error_msg


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(description="Generate Bacformer embeddings for Klebsiella genomes")
    parser.add_argument(
        "--n",
        type=int,
        default=None,
        help="Limit number of genomes to process (for testing)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=128,
        help="Batch size for ESM embedding computation (default: 128)",
    )
    parser.add_argument(
        "--max-proteins",
        type=int,
        default=6000,
        help="Maximum number of proteins per genome (default: 6000)",
    )
    parser.add_argument(
        "--max-contigs",
        type=int,
        default=1000,
        help="Maximum number of contigs per genome (default: 1000)",
    )
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip genomes that have already been processed",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda:0",
        help="Device to use for inference (default: cuda:0)",
    )
    parser.add_argument(
        "--start-idx",
        type=int,
        default=None,
        help="Start index for processing files (for array jobs)",
    )
    parser.add_argument(
        "--end-idx",
        type=int,
        default=None,
        help="End index for processing files (for array jobs)",
    )

    args = parser.parse_args()

    # Setup input directory path
    input_dir = data.klebsiella_protein_sequences_dir
    logger.info(f"Input directory: {input_dir}")

    # Setup output directories
    esm_dir = data.klebsiella_esm_embeddings_dir
    bacformer_dir = data.klebsiella_bacformer_embeddings_dir
    
    # Create output directories if they don't exist
    esm_dir.mkdir(parents=True, exist_ok=True)
    bacformer_dir.mkdir(parents=True, exist_ok=True)
    logger.info(f"ESM embeddings directory: {esm_dir}")
    logger.info(f"Bacformer embeddings directory: {bacformer_dir}")

    # Find all protein sequence parquet files (takes first n if --n is set)
    protein_files = find_protein_sequence_files(input_dir, limit=args.n)

    if not protein_files:
        logger.error(f"No protein sequence parquet files found in {input_dir}")
        logger.error("Please run generate_protein_sequences.py first to generate protein sequences")
        sys.exit(1)

    # Filter out files that already have embeddings if requested
    if args.skip_existing:
        original_count = len(protein_files)
        protein_files = [
            f for f in protein_files 
            if not check_embeddings_exist(extract_sample_id(f), esm_dir, bacformer_dir)
        ]
        skipped = original_count - len(protein_files)
        if skipped > 0:
            logger.info(f"Skipping {skipped} genomes that already have embeddings")

    if not protein_files:
        logger.info("All genomes already have embeddings")
        return

    # Apply array job slicing if indices provided
    if args.start_idx is not None and args.end_idx is not None:
        total_files = len(protein_files)
        protein_files = protein_files[args.start_idx:args.end_idx]
        logger.info(f"Array job slice: processing files {args.start_idx} to {args.end_idx} of {total_files}")
        logger.info(f"Files in this slice: {len(protein_files)}")

    # Setup device
    device = args.device
    logger.info(f"Using device: {device}")

    # Load ESM model (protein language model) - ONCE
    logger.info("Loading ESM model (ESM++)...")
    esm_model, esm_tokenizer = load_plm(
        model_path="Synthyra/ESMplusplus_small",
        model_type="esmc",
    )
    logger.info("ESM model loaded")

    # Load Bacformer model - ONCE
    logger.info("Loading Bacformer model...")
    bacformer_model = (
        AutoModel.from_pretrained(
            "macwiatrak/bacformer-large-masked-MAG",
            trust_remote_code=True,
        )
        .to(device)
        .eval()
        .to(torch.bfloat16)
    )
    logger.info("Bacformer model loaded")

    # Process genomes
    results = {"success": [], "failed": []}
    error_log = []
    genome_times = []

    # Record start time
    overall_start_time = time.time()
    logger.info("=" * 80)
    logger.info(f"STARTING PROCESSING: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info(f"Total genomes to process: {len(protein_files)}")
    logger.info("=" * 80)

    for idx, protein_file in enumerate(tqdm(protein_files, desc="Processing genomes"), 1):
        genome_start = time.time()

        sample_id, success, error_msg = process_genome_from_protein_sequences(
            protein_file,
            esm_model,
            esm_tokenizer,
            bacformer_model,
            device,
            esm_dir,
            bacformer_dir,
            batch_size=args.batch_size,
            max_proteins=args.max_proteins,
            max_contigs=args.max_contigs,
        )

        genome_elapsed = time.time() - genome_start
        genome_times.append(genome_elapsed)

        if success:
            results["success"].append(sample_id)
            logger.info(f"[{idx}/{len(protein_files)}] {sample_id}: SUCCESS ({genome_elapsed:.1f}s)")
        else:
            results["failed"].append(sample_id)
            error_log.append({"sample_id": sample_id, "error": error_msg})
            logger.warning(f"[{idx}/{len(protein_files)}] {sample_id}: FAILED ({genome_elapsed:.1f}s)")

        # Log timing estimates every 10 genomes
        if idx % 10 == 0 and genome_times:
            avg_time = sum(genome_times) / len(genome_times)
            remaining = len(protein_files) - idx
            est_remaining = timedelta(seconds=int(avg_time * remaining))
            logger.info(f"Average time per genome: {avg_time:.1f}s, Estimated time remaining: {est_remaining}")

    # Calculate total elapsed time
    overall_elapsed = time.time() - overall_start_time

    # Summary
    logger.info("=" * 80)
    logger.info(f"PROCESSING COMPLETE: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info("=" * 80)
    logger.info(f"Total time elapsed: {timedelta(seconds=int(overall_elapsed))}")
    logger.info(f"Successfully processed: {len(results['success'])} genomes")
    logger.info(f"Failed: {len(results['failed'])} genomes")

    if genome_times:
        avg_time = sum(genome_times) / len(genome_times)
        min_time = min(genome_times)
        max_time = max(genome_times)
        logger.info(f"Timing statistics:")
        logger.info(f"  - Average: {avg_time:.1f}s per genome")
        logger.info(f"  - Min: {min_time:.1f}s")
        logger.info(f"  - Max: {max_time:.1f}s")
        logger.info(f"  - Total genomes processed: {len(genome_times)}")

    if error_log:
        error_log_path = Path("bacformer_embeddings_errors.log")
        with open(error_log_path, "w") as f:
            for entry in error_log:
                f.write(f"{entry['sample_id']}: {entry['error']}\n")
        logger.info(f"Error details saved to {error_log_path}")

    logger.info("=" * 80)


if __name__ == "__main__":
    main()
